mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:question_id>/", views.DetailView.as_view(), name="detail"),
    path("<int:question_id>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path('add/', views.add_question, name='add_question'),
    path('save/', views.save_question, name='save_question'),
    path('<int:question_id>/choice/add/', views.add_choice, name='add_choice'),
    path('<int:question_id>/choice/save/', views.save_choice, name='save_choice'),
    path('<int:question_id>/edit/', views.edit_question, name='edit_question'),
    path('<int:question_id>/delete/', views.delete_question, name='delete_question'),
    path('<int:question_id>/choice/<int:choice_id>/edit/', views.edit_choice, name='edit_choice'),
    path('<int:question_id>/choice/<int:choice_id>/update/', views.update_choice, name='update_choice'),
    path('<int:question_id>/choice/<int:choice_id>/delete/', views.delete_choice, name='delete_choice'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponse
from .models import Question, Choice
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    pk_url_kwarg = 'question_id'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    context_object_name = 'question'
    
    def get_object(self):
        # Get the question_id from URL and return the Question object
        question_id = self.kwargs.get('question_id')
        return get_object_or_404(Question, pk=question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def add_question(request):
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        if question_text:
            question = Question.objects.create(
                question_text=question_text,
                pub_date=timezone.now()
            )
            return redirect('polls:detail', question_id=question.id)
    return render(request, 'polls/add_question.html')

def save_question(request):
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        pub_date = request.POST.get('pub_date')
        question = Question.objects.create(
            question_text=question_text,
            pub_date=timezone.now() if not pub_date else pub_date
        )
        return redirect('polls:detail', question_id=question.id)
    return redirect('polls:index')

def add_choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/add_choice.html', {'question': question})

def save_choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        choice_text = request.POST.get('choice_text')
        if choice_text:
            question.choice_set.create(choice_text=choice_text)
            return redirect('polls:detail', question_id=question_id)
    return redirect('polls:detail', question_id=question_id)

def edit_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        if question_text:
            question.question_text = question_text
            question.save()
            return redirect('polls:index')
    
    return render(request, 'polls/edit_question.html', {'question': question})

def delete_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('polls:index')

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def edit_choice(request, question_id, choice_id):
    question = get_object_or_404(Question, pk=question_id)
    choice = get_object_or_404(Choice, pk=choice_id)
    return render(request, 'polls/edit_choice.html', {
        'question': question,
        'choice': choice
    })

def update_choice(request, question_id, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    if request.method == 'POST':
        choice_text = request.POST.get('choice_text')
        if choice_text:
            choice.choice_text = choice_text
            choice.save()
    return redirect('polls:detail', question_id=question_id)

def delete_choice(request, question_id, choice_id):
    choice = get_object_or_404(Choice, pk=choice_id)
    choice.delete()
    return redirect('polls:detail', question_id=question_id)

polls/templates/polls/add_choice.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Add Choice</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div class="container">
            <h1>Add Choice for "{{ question.question_text }}"</h1>
            <form action="{% url 'polls:save_choice' question.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="choice_text">Choice:</label>
                    <input type="text" id="choice_text" name="choice_text" required>
                </div>
                <div class="button-group">
                    <input type="submit" value="Add Choice">
                    <a href="{% url 'polls:detail' question.id %}"><button type="button" class="cancel-button">Cancel</button></a>
                </div>
            </form>
        </div>
    </body>
</html>

polls/templates/polls/add_question.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Add New Question</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div class="container">
            <h1>Add New Question</h1>
            <form action="{% url 'polls:save_question' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="question_text">Question:</label>
                    <input type="text" id="question_text" name="question_text" required>
                </div>
                <div class="form-group">
                    <label for="pub_date">Publication Date:</label>
                    <input type="datetime-local" id="pub_date" name="pub_date" required>
                </div>
                <div class="button-group">
                    <input type="submit" value="Add Question">
                    <a href="{% url 'polls:index' %}"><button type="button" class="cancel-button">Cancel</button></a>
                </div>
            </form>
        </div>
    </body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Poll Question</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    </head>
    <body>
        <div class="container">
            <form action="{% url 'polls:vote' question.id %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend><h1>{{ question.question_text }}</h1></legend>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% for choice in question.choice_set.all %}
                        <div class="choice-item">
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                            <div class="choice-actions">
                                <a href="{% url 'polls:edit_choice' question.id choice.id %}" class="edit-choice-btn">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="#" onclick="confirmDeleteChoice('{{ choice.id }}', '{{ question.id }}')" class="delete-choice-btn">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </fieldset>
                <div class="button-group">
                    <input type="submit" value="Vote">
                    <a href="{% url 'polls:add_choice' question.id %}"><button type="button">Add Choice</button></a>
                    <a href="{% url 'polls:index' %}"><button type="button">Back to Questions</button></a>
                </div>
            </form>
        </div>

        <script>
            function confirmDeleteChoice(choiceId, questionId) {
                if (confirm('Are you sure you want to delete this choice?')) {
                    window.location.href = `/polls/${questionId}/choice/${choiceId}/delete/`;
                }
            }
        </script>
    </body>
</html>

polls/templates/polls/edit_choice.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Edit Choice</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    </head>
    <body>
        <div class="container">
            <h1>Edit Choice for "{{ question.question_text }}"</h1>
            <form action="{% url 'polls:update_choice' question.id choice.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="choice_text">Choice:</label>
                    <input type="text" id="choice_text" name="choice_text" value="{{ choice.choice_text }}" required>
                </div>
                <div class="button-group">
                    <input type="submit" value="Update Choice">
                    <a href="{% url 'polls:detail' question_id=question.id %}"><button type="button" class="cancel-button">Cancel</button></a>
                </div>
            </form>
        </div>
    </body>
</html> 

polls/templates/polls/edit_question.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Edit Question</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div class="container">
        <h1>Edit Question</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="question_text">Question:</label>
                <input type="text" name="question_text" id="question_text" value="{{ question.question_text }}" required>
            </div>
            <div class="button-group">
                <button type="submit">Save Changes</button>
                <a href="{% url 'polls:index' %}"><button type="button" class="cancel-button">Cancel</button></a>
            </div>
        </form>
    </div>
</body>
</html> 

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Poll App</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
        <!-- Add Font Awesome for the ellipsis icon -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
        <script src="{% static 'polls/dropdown.js' %}"></script>
    </head>
    <body>
        <div class="dropdown-portal"></div>
        <div class="container">
            <h1>Welcome to Poll App</h1>
            <h1>Questions</h1>
            {% if latest_question_list %}
                <ul class="question-list">
                    {% for question in latest_question_list %}
                        <li class="question-item">
                            <a href="{% url 'polls:detail' question.id %}" class="question-link">
                                <span class="question-text">{{ question.question_text }}</span>
                                <span class="question-date">{{ question.pub_date|date:"M d, Y g:i A" }}</span>
                            </a>
                            <div class="dropdown-wrapper">
                                <div class="dropdown">
                                    <button class="dropbtn"><i class="fas fa-ellipsis-v"></i></button>
                                    <div class="dropdown-content">
                                        <a href="{% url 'polls:edit_question' question.id %}" class="edit-btn">Edit</a>
                                        <a href="#" class="delete-btn" onclick="confirmDelete('{{ question.id }}')">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            <div class="button-group">
                <a href="{% url 'polls:add_question' %}"><button type="button">Add New Question</button></a>
            </div>
        </div>

        <!-- Add JavaScript for delete confirmation -->
        <script>
            // Add this function for dropdown toggle
            function toggleDropdown(event, button) {
                event.stopPropagation(); // Prevent event from bubbling up
                const dropdowns = document.getElementsByClassName("dropdown-content");
                
                // Close all other dropdowns
                for (let dropdown of dropdowns) {
                    if (dropdown !== button.nextElementSibling) {
                        dropdown.classList.remove('show');
                    }
                }
                
                // Toggle current dropdown
                button.nextElementSibling.classList.toggle('show');
            }

            // Close dropdown when clicking outside
            window.onclick = function(event) {
                if (!event.target.matches('.dropbtn') && !event.target.matches('.fa-ellipsis-v')) {
                    const dropdowns = document.getElementsByClassName("dropdown-content");
                    for (let dropdown of dropdowns) {
                        if (dropdown.classList.contains('show')) {
                            dropdown.classList.remove('show');
                        }
                    }
                }
            }

            function confirmDelete(questionId) {
                if (confirm('Are you sure you want to delete this question?')) {
                    window.location.href = "{% url 'polls:index' %}" + questionId + "/delete/";
                }
            }
        </script>
    </body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Poll Results</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  </head>
  <body>
    <div class="container">
      <h1>{{ question.question_text }}</h1>

      <ul class="results-list">
        {% for choice in question.choice_set.all %}
          <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
      </ul>
      <div class="button-group">
        <a href="{% url 'polls:detail' question_id=question.id %}"><button type="button">Vote again?</button></a>
        <a href="{% url 'polls:index' %}"><button type="button">Back to Questions</button></a>
      </div>
    </div>
  </body>
</html>